services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    dev-db:
      image: postgres:17.2-alpine3.20
      restart: always
      env_file:
        - ./.env
      volumes: 
        - ./scripts:/docker-entrypoint-initdb.d

      ports:
        - "5432:5432"
      
